#pragma config(Motor,  port1,           right,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port5,           claw,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          left,          tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  while(1 == 1){
    //Right side of the robot is controlled by the right joystick, Y-axis
    motor[right] = vexRT[Ch2];
    //motor[backRightMotor]  = vexRT[Ch2];
    //Left side of the robot is controlled by the left joystick, Y-axis
    motor[left] = vexRT[Ch3];
    //motor[backLeftMotor]  = vexRT[Ch3];
    //motor[arm] = vexRT[Btn6];
    	while (vexRT[Btn5U] == 1){
    		motor[arm]=63;
    	}
    	while (vexRT[Btn5D] == 1){
    		motor[arm] = -63;
    	}
   motor[arm] = 15;
   //claw
   		while (vexRT[Btn6U] == 1){
    		motor[claw]=63;
    	}
    	while (vexRT[Btn6D] == 1){
    		motor[claw] = -63;
    	}
   motor[claw] = 0;
  }
}
